name: HologramPlugin
version: '${project.version}'
main: xyz.wtje.holograms.paper.HologramPlugin
api-version: '1.19'
authors: [wtje]
description: Professional hologram plugin using Display Entities and Armor Stand fallback

commands:
  holo:
    description: Main hologram command
    usage: /<command> <create|remove|edit|move|tp|copy|list> [args...]
    permission: holo.use
    aliases: [hologram, holograms]

permissions:
  holo.use:
    description: Basic hologram usage
    default: true
  holo.create:
    description: Create holograms
    default: op
  holo.remove:
    description: Remove holograms
    default: op
  holo.edit:
    description: Edit holograms
    default: op
  holo.admin:
    description: Full hologram administration
    default: op
    children:
      - holo.create
      - holo.remove
      - holo.edit
      - holo.reload
  holo.reload:
    description: Reload holograms
    default: op

softdepend: [PlaceholderAPI, ViaVersion, packetevents]