name: Build and Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Extract version from tag
        if: github.event_name == 'release'
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Building version: $VERSION"

      - name: Use manual version (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          # Fallback to tag name if present, else default to 0.0.0
          VERSION=${GITHUB_REF_NAME#v}
          if [ -z "$VERSION" ]; then VERSION=0.0.0; fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Building version: $VERSION"

      - name: Set project version
        run: mvn -B -ntp versions:set -DnewVersion=${{ env.VERSION }} -DgenerateBackupPoms=false

      - name: Build
        run: mvn -B -ntp -DskipTests clean package

      - name: Find and upload JAR
        run: |
          JAR_FILE="modern-paper/target/modern-paper-${{ env.VERSION }}-shaded.jar"
          
          if [ ! -f "$JAR_FILE" ]; then
            echo "JAR not found: $JAR_FILE"
            echo "Contents of modern-paper/target/:"
            ls -la modern-paper/target/
            exit 1
          fi
          
          echo "Found JAR: $JAR_FILE"
          echo "Size: $(du -h "$JAR_FILE" | cut -f1)"
          
          # Upload to release
          gh release upload ${{ github.event.release.tag_name }} "$JAR_FILE" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
